import { Product, Clinic, KpiData, AlertItem, ModuleStats } from "./types";

export const products: Product[] = [
  {
    id: "ai-triage",
    name: "AI問診エンジン",
    nameEn: "AI Triage Engine",
    description:
      "AI問診でリスクスコアと推奨検査を自動算出。診察前に90%の情報収集を完了し、医師の診察効率を劇的に向上。",
    monthlyPrice: 30000,
    icon: "Brain",
    category: "external",
    features: [
      "自然言語AI問診",
      "リスクスコア自動算出",
      "推奨検査提案",
      "トリアージ自動分類",
      "多言語対応",
      "カルテ自動下書き",
    ],
    color: "#6366f1",
  },
  {
    id: "online-consultation",
    name: "オンライン診療PF",
    nameEn: "Online Consultation Platform",
    description:
      "ビデオ診察・決済・処方箋発行をワンストップで。再診患者の通院負担をゼロにし、治療中断率を劇的に低減。",
    monthlyPrice: 20000,
    icon: "Video",
    category: "external",
    features: [
      "HD ビデオ診察",
      "クレジットカード決済",
      "電子処方箋連携",
      "予約・リマインド",
      "録画・記録",
      "待合室機能",
    ],
    color: "#06b6d4",
  },
  {
    id: "remote-monitoring",
    name: "遠隔モニタリング",
    nameEn: "Remote Monitoring",
    description:
      "血圧・血糖・体重・心拍を常時収集。AIが異常を検知し自動でアラート。予防医療の要。",
    monthlyPrice: 15000,
    icon: "Activity",
    category: "external",
    features: [
      "バイタルデータ常時収集",
      "AI異常検知アラート",
      "トレンド分析",
      "患者別ダッシュボード",
      "IoTデバイス連携",
      "自動レポート生成",
    ],
    color: "#10b981",
  },
  {
    id: "patient-app",
    name: "患者アプリ",
    nameEn: "Patient App",
    description:
      "患者向けダッシュボード。薬歴・バイタル・予約・リマインドを一元管理。治療継続を患者側から支援。",
    monthlyPrice: 10000,
    icon: "Smartphone",
    category: "external",
    features: [
      "健康ダッシュボード",
      "薬歴管理",
      "服薬リマインド",
      "予約管理",
      "医師メッセージ",
      "検査結果閲覧",
    ],
    color: "#f59e0b",
  },
  {
    id: "partner-network",
    name: "提携NW接続",
    nameEn: "Partner Network",
    description:
      "検査機関・薬局とのAPI連携ネットワーク。検査オーダーから結果受信、処方箋送信までシームレスに。",
    monthlyPrice: 10000,
    icon: "Network",
    category: "external",
    features: [
      "検査機関API連携",
      "薬局API連携",
      "結果自動取込",
      "処方箋電子送信",
      "提携先検索",
      "在庫確認",
    ],
    color: "#8b5cf6",
  },
  {
    id: "emr",
    name: "電子カルテ",
    nameEn: "Electronic Medical Records",
    description:
      "AI問診と完全統合された次世代電子カルテ。問診→カルテ記入がシームレス。自社クリニック専用。",
    monthlyPrice: 80000,
    icon: "FileText",
    category: "fullstack-only",
    features: [
      "AI自動カルテ記入",
      "SOAP形式対応",
      "テンプレート管理",
      "画像管理",
      "紹介状作成",
      "検査結果統合",
    ],
    color: "#ec4899",
  },
  {
    id: "receipt-computer",
    name: "レセコン",
    nameEn: "Receipt Computer",
    description:
      "レセプト自動生成・オンライン請求。カルテと完全連動し、診療→請求が一気通貫。自社クリニック専用。",
    monthlyPrice: 70000,
    icon: "Calculator",
    category: "fullstack-only",
    features: [
      "レセプト自動生成",
      "オンライン請求",
      "点数自動計算",
      "返戻管理",
      "統計・分析",
      "カルテ連動",
    ],
    color: "#f97316",
  },
];

export const clinics: Clinic[] = [
  {
    id: "cl-001",
    name: "田中内科クリニック",
    type: "partner",
    status: "active",
    plan: "bundle",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
      "patient-app",
      "partner-network",
    ],
    address: "東京都渋谷区神宮前3-1-15",
    doctorName: "田中 一郎",
    specialty: "内科・生活習慣病",
    monthlyPatients: 450,
    onlineRatio: 0.35,
    joinedAt: "2026-07-01",
    mrr: 65000,
    contactEmail: "tanaka@clinic.example.com",
    contactPhone: "03-1234-5678",
  },
  {
    id: "cl-002",
    name: "佐藤ファミリークリニック",
    type: "partner",
    status: "active",
    plan: "individual",
    subscribedProducts: ["ai-triage", "online-consultation"],
    address: "東京都世田谷区駒沢2-8-10",
    doctorName: "佐藤 花子",
    specialty: "内科・小児科",
    monthlyPatients: 380,
    onlineRatio: 0.2,
    joinedAt: "2026-08-15",
    mrr: 50000,
    contactEmail: "sato@family-clinic.example.com",
    contactPhone: "03-2345-6789",
  },
  {
    id: "cl-003",
    name: "山本糖尿病・代謝クリニック",
    type: "partner",
    status: "active",
    plan: "bundle",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
      "patient-app",
      "partner-network",
    ],
    address: "東京都新宿区西新宿1-2-3",
    doctorName: "山本 健太",
    specialty: "糖尿病・内分泌科",
    monthlyPatients: 520,
    onlineRatio: 0.45,
    joinedAt: "2026-07-15",
    mrr: 65000,
    contactEmail: "yamamoto@dm-clinic.example.com",
    contactPhone: "03-3456-7890",
  },
  {
    id: "cl-004",
    name: "鈴木循環器内科",
    type: "partner",
    status: "trial",
    plan: "individual",
    subscribedProducts: ["ai-triage", "remote-monitoring"],
    address: "東京都中央区日本橋4-5-6",
    doctorName: "鈴木 太郎",
    specialty: "循環器内科",
    monthlyPatients: 300,
    onlineRatio: 0.1,
    joinedAt: "2026-10-01",
    mrr: 45000,
    contactEmail: "suzuki@cardio.example.com",
    contactPhone: "03-4567-8901",
  },
  {
    id: "cl-005",
    name: "中村総合クリニック",
    type: "partner",
    status: "active",
    plan: "individual",
    subscribedProducts: ["online-consultation", "patient-app"],
    address: "東京都港区六本木7-8-9",
    doctorName: "中村 美咲",
    specialty: "総合内科",
    monthlyPatients: 600,
    onlineRatio: 0.3,
    joinedAt: "2026-08-01",
    mrr: 30000,
    contactEmail: "nakamura@general.example.com",
    contactPhone: "03-5678-9012",
  },
  {
    id: "cl-006",
    name: "伊藤メディカルクリニック",
    type: "partner",
    status: "onboarding",
    plan: "bundle",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
      "patient-app",
      "partner-network",
    ],
    address: "東京都品川区大崎1-3-5",
    doctorName: "伊藤 真一",
    specialty: "内科・呼吸器科",
    monthlyPatients: 0,
    onlineRatio: 0,
    joinedAt: "2026-11-01",
    mrr: 65000,
    contactEmail: "ito@medical.example.com",
    contactPhone: "03-6789-0123",
  },
  {
    id: "cl-007",
    name: "高橋生活習慣病クリニック",
    type: "partner",
    status: "active",
    plan: "individual",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
    ],
    address: "東京都豊島区池袋2-4-6",
    doctorName: "高橋 雄一",
    specialty: "生活習慣病",
    monthlyPatients: 420,
    onlineRatio: 0.25,
    joinedAt: "2026-09-01",
    mrr: 65000,
    contactEmail: "takahashi@lifestyle.example.com",
    contactPhone: "03-7890-1234",
  },
  {
    id: "cl-008",
    name: "渡辺内科・糖尿病クリニック",
    type: "partner",
    status: "churned",
    plan: "individual",
    subscribedProducts: [],
    address: "東京都杉並区高円寺5-7-9",
    doctorName: "渡辺 正",
    specialty: "糖尿病内科",
    monthlyPatients: 0,
    onlineRatio: 0,
    joinedAt: "2026-07-01",
    mrr: 0,
    contactEmail: "watanabe@dm2.example.com",
    contactPhone: "03-8901-2345",
  },
  {
    id: "cl-009",
    name: "Medixusクリニック 渋谷",
    type: "owned",
    status: "active",
    plan: "fullstack",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
      "patient-app",
      "partner-network",
      "emr",
      "receipt-computer",
    ],
    address: "東京都渋谷区道玄坂1-10-8",
    doctorName: "管理医師 A",
    specialty: "内科・生活習慣病・AGA・ED",
    monthlyPatients: 800,
    onlineRatio: 0.65,
    joinedAt: "2027-03-01",
    mrr: 1050000,
    contactEmail: "shibuya@medixus-clinic.example.com",
    contactPhone: "03-9012-3456",
  },
  {
    id: "cl-010",
    name: "小林皮膚科クリニック",
    type: "partner",
    status: "active",
    plan: "individual",
    subscribedProducts: ["online-consultation", "patient-app"],
    address: "東京都目黒区自由が丘2-3-1",
    doctorName: "小林 直美",
    specialty: "皮膚科",
    monthlyPatients: 350,
    onlineRatio: 0.15,
    joinedAt: "2026-09-15",
    mrr: 30000,
    contactEmail: "kobayashi@derma.example.com",
    contactPhone: "03-0123-4567",
  },
  {
    id: "cl-011",
    name: "加藤内科循環器クリニック",
    type: "partner",
    status: "active",
    plan: "bundle",
    subscribedProducts: [
      "ai-triage",
      "online-consultation",
      "remote-monitoring",
      "patient-app",
      "partner-network",
    ],
    address: "横浜市青葉区あざみ野1-5-8",
    doctorName: "加藤 隆",
    specialty: "内科・循環器",
    monthlyPatients: 480,
    onlineRatio: 0.4,
    joinedAt: "2026-08-01",
    mrr: 65000,
    contactEmail: "kato@heart.example.com",
    contactPhone: "045-1234-5678",
  },
  {
    id: "cl-012",
    name: "松本腎臓内科クリニック",
    type: "partner",
    status: "trial",
    plan: "individual",
    subscribedProducts: ["ai-triage"],
    address: "千葉市中央区富士見1-2-3",
    doctorName: "松本 守",
    specialty: "腎臓内科",
    monthlyPatients: 250,
    onlineRatio: 0.05,
    joinedAt: "2026-10-15",
    mrr: 30000,
    contactEmail: "matsumoto@kidney.example.com",
    contactPhone: "043-2345-6789",
  },
];

export const kpiHistory: KpiData[] = [
  {
    month: "2026-07",
    partnerClinics: 3,
    ownedClinics: 0,
    totalPatients: 50,
    onlinePatients: 15,
    mrr: 195000,
    churnRate: 0,
    continuationRate: 100,
  },
  {
    month: "2026-08",
    partnerClinics: 6,
    ownedClinics: 0,
    totalPatients: 150,
    onlinePatients: 52,
    mrr: 340000,
    churnRate: 0,
    continuationRate: 95,
  },
  {
    month: "2026-09",
    partnerClinics: 8,
    ownedClinics: 0,
    totalPatients: 300,
    onlinePatients: 120,
    mrr: 455000,
    churnRate: 0,
    continuationRate: 92,
  },
  {
    month: "2026-10",
    partnerClinics: 10,
    ownedClinics: 0,
    totalPatients: 500,
    onlinePatients: 200,
    mrr: 545000,
    churnRate: 5,
    continuationRate: 90,
  },
  {
    month: "2026-11",
    partnerClinics: 11,
    ownedClinics: 0,
    totalPatients: 700,
    onlinePatients: 300,
    mrr: 610000,
    churnRate: 5,
    continuationRate: 88,
  },
  {
    month: "2026-12",
    partnerClinics: 11,
    ownedClinics: 0,
    totalPatients: 1000,
    onlinePatients: 430,
    mrr: 610000,
    churnRate: 8,
    continuationRate: 87,
  },
  {
    month: "2027-01",
    partnerClinics: 11,
    ownedClinics: 0,
    totalPatients: 1250,
    onlinePatients: 560,
    mrr: 610000,
    churnRate: 5,
    continuationRate: 89,
  },
  {
    month: "2027-02",
    partnerClinics: 11,
    ownedClinics: 0,
    totalPatients: 1500,
    onlinePatients: 700,
    mrr: 610000,
    churnRate: 3,
    continuationRate: 91,
  },
  {
    month: "2027-03",
    partnerClinics: 11,
    ownedClinics: 1,
    totalPatients: 1750,
    onlinePatients: 850,
    mrr: 1660000,
    churnRate: 3,
    continuationRate: 92,
  },
];

export const alerts: AlertItem[] = [
  {
    id: "a-001",
    type: "success",
    title: "新規提携",
    message: "伊藤メディカルクリニックがバンドルプランで契約しました",
    clinicId: "cl-006",
    timestamp: "2026-11-01T10:30:00",
  },
  {
    id: "a-002",
    type: "warning",
    title: "トライアル期限",
    message: "鈴木循環器内科のトライアル期限が2週間後に迫っています",
    clinicId: "cl-004",
    timestamp: "2026-10-18T09:00:00",
  },
  {
    id: "a-003",
    type: "error",
    title: "解約",
    message: "渡辺内科・糖尿病クリニックが全製品を解約しました",
    clinicId: "cl-008",
    timestamp: "2026-10-15T14:20:00",
  },
  {
    id: "a-004",
    type: "info",
    title: "PMF指標達成",
    message: "月間オンライン診療数が300件を突破しました",
    timestamp: "2026-09-28T16:00:00",
  },
  {
    id: "a-005",
    type: "success",
    title: "自社クリニック開設",
    message: "Medixusクリニック渋谷が開設準備完了しました",
    clinicId: "cl-009",
    timestamp: "2027-02-28T12:00:00",
  },
  {
    id: "a-006",
    type: "info",
    title: "MRR更新",
    message: "MRRが150万円を超え、GO判断基準をクリアしました",
    timestamp: "2027-03-01T00:00:00",
  },
];

export const moduleStats: ModuleStats[] = [
  {
    productId: "ai-triage",
    activeClinics: 8,
    totalSessions: 12500,
    avgSessionTime: 4.2,
    satisfaction: 4.6,
    trend: 12,
  },
  {
    productId: "online-consultation",
    activeClinics: 8,
    totalSessions: 8700,
    avgSessionTime: 8.5,
    satisfaction: 4.4,
    trend: 18,
  },
  {
    productId: "remote-monitoring",
    activeClinics: 5,
    totalSessions: 45000,
    avgSessionTime: 0,
    satisfaction: 4.3,
    trend: 25,
  },
  {
    productId: "patient-app",
    activeClinics: 6,
    totalSessions: 32000,
    avgSessionTime: 3.1,
    satisfaction: 4.5,
    trend: 15,
  },
  {
    productId: "partner-network",
    activeClinics: 4,
    totalSessions: 5600,
    avgSessionTime: 0,
    satisfaction: 4.1,
    trend: 8,
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getClinic(id: string): Clinic | undefined {
  return clinics.find((c) => c.id === id);
}

export function getActiveClinics(): Clinic[] {
  return clinics.filter((c) => c.status === "active" || c.status === "trial");
}

export function getPartnerClinics(): Clinic[] {
  return clinics.filter((c) => c.type === "partner");
}

export function getOwnedClinics(): Clinic[] {
  return clinics.filter((c) => c.type === "owned");
}

export function getTotalMRR(): number {
  return clinics
    .filter((c) => c.status === "active" || c.status === "trial")
    .reduce((sum, c) => sum + c.mrr, 0);
}

export function getExternalProducts(): Product[] {
  return products.filter((p) => p.category === "external");
}

export function getFullstackProducts(): Product[] {
  return products;
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("ja-JP", {
    style: "currency",
    currency: "JPY",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatNumber(num: number): string {
  return new Intl.NumberFormat("ja-JP").format(num);
}
